# -*- coding: utf-8 -*-
"""assignment plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PGHhBLcvbTeQLhLtpIIdEu1LqehtOIfc
"""

'''Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.'''

import seaborn as sns
import plotly.graph_objects as go
titanic = sns.load_dataset('titanic')
titanic

fig=go.Figure(data=[go.Scatter(x=titanic.age,y=titanic.fare,mode='markers')])
fig.show()

#Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express.

import plotly.express as px
import seaborn as sns

# Load the tips dataset from seaborn
tips = sns.load_dataset("tips")

# Create a box plot using Plotly Express
fig = px.box(tips, x="day", y="total_bill", points="all")

# Customize the layout if needed
fig.update_layout(
    title="Box Plot of Total Bill Amount by Day",
    xaxis_title="Day",
    yaxis_title="Total Bill Amount",
)

# Show the plot
fig.show()

'''Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.'''

import plotly.express as px
import seaborn as sns

# Load the tips dataset from seaborn
tips = sns.load_dataset("tips")

# Create a histogram with custom parameters
fig = px.histogram(
    tips,
    x="sex",
    y="total_bill",
    color="day",
    facet_col="smoker",
    pattern_shape="smoker",
    marginal="box",
    title="Histogram of Total Bill Amount by Sex",
    labels={"total_bill": "Total Bill Amount"},
)

# Show the plot
fig.show()

'''Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.'''

import plotly.express as px
from sklearn.datasets import load_iris
import pandas as pd

# Load the iris dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# Create a scatter matrix plot
fig = px.scatter_matrix(
    iris_df,
    dimensions=iris.feature_names,
    color="species",
    title="Scatter Matrix Plot of Iris Dataset",
    labels={col: col.replace(' (cm)', '') for col in iris_df.columns[:-1]}
)

# Show the plot
fig.show()

'''Q5. What is Distplot? Using Plotly express, plot a distplot.


A distplot (distribution plot) is a graphical representation that combines a histogram with a kernel density estimate (KDE) plot.
It is used to visualize the distribution of a univariate set of observations, providing insights into the underlying probability density
 function.'''

import plotly.express as px
import seaborn as sns

# Load the tips dataset from seaborn
tips = sns.load_dataset("tips")

# Create a distplot using Plotly Express
fig = px.histogram(
    tips,
    x="total_bill",
    marginal="rug",
    title="Distribution Plot of Total Bill Amount",
    labels={"total_bill": "Total Bill Amount"},
)

# Show the plot
fig.show()

